version: '2'

services:
  keycloak:
    image: microcks/microcks-keycloak:20.0.1
    container_name: microcks-keycloak-test
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KEYCLOAK_IMPORT: "/tmp/microcks-realm.json"
      KC_HOSTNAME_ADMIN_URL: "http://localhost:8180"
      KC_HOSTNAME_URL: "http://localhost:8180"
    volumes: 
      - "./microcks-realm/microcks-realm-sample.json:/tmp/microcks-realm.json"
    command:
      - start-dev